---
name: environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - setuptools=60.1
  - cartopy=0.20.1
  - coverage=6.2
  - coveralls=3.3
  - gdal=3.4
  - ipdb=0.13
  - ipython=7.30
  - matplotlib=3.5
  - mock=4.0
  - netcdf4=1.5
  - nose=1.3
  - numpy=1.21
  - pillow=8.4
  - pip=21
  - python-dateutil=2.8
  - PyYAML<6.0
  - scipy=1.7
  - urllib3=1.26
  - pip:
      - pythesint==1.6.6
