---
name: environment
channels:
  - defaults
dependencies:
  - python=3.7.16
  - conda=23.1.0
  - nomkl=3.0
  - openblas=0.3.21

  - cartopy=0.18.0
  - coverage=6.3.2
  - coveralls=1.7.0
  - gdal=3.6.0
  - ipython=7.31.1
  - matplotlib-base=3.5.3
  - mock=4.0.3
  - netcdf4=1.6.2
  - nose=1.3.7
  - numpy-base=1.21.5
  - pillow=9.4.0
  - pip=22.3.1
  - PyYAML=5.4.1
  - scipy=1.7.3
  - setuptools=65.6.3
  - urllib3=1.26.14
  - pip:
      - pythesint==1.6.6
