---
name: environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.5
  - conda=23.10.0

  - cartopy=0.22.0
  - coverage=7.2.2
  - coveralls=1.7.0
  - gdal=3.7.3
  - ipython=8.15.0
  - matplotlib=3.8.0
  - mock=4.0.3
  - netcdf4=1.6.5
  - nose=1.3.7
  - numpy=1.26.0
  - pillow=10.1.0
  - pip=23.3
  - PyYAML=5.4.1
  - scipy=1.11.3
  - setuptools=68.0.0
  - urllib3=2.0.3
  - pip:
      - pythesint==1.6.6
