---
name: environment
channels:
  - defaults
dependencies:
  - python=3.9.18
  - conda=23.10.0

  - cartopy=0.18.0
  - coverage=7.2.2
  - coveralls=1.7.0
  - gdal=3.6.2
  - ipython=8.15.0
  - matplotlib-base=3.5.3
  - mock=4.0.3
  - netcdf4=1.6.2
  - nose=1.3.7
  - numpy-base=1.26.0
  - pillow=10.0.1
  - pip=23.3
  - PyYAML=5.4.1
  - scipy=1.11.3
  - setuptools=68.0.0
  - shapely=1.8.4
  - urllib3=1.26.18
  - pip:
      - pythesint==1.6.6
